title: Built Environment
description: A sustainable community provides quality, choice, and access in the built environment, where people live, work, and play.
lead: A sustainable built environment is characterized by
subsections:
  - title: Ambient Noise & Light
    graphic: http://placehold.it/350x350
    content: |
            Here is some content from subsection "Ambient Noise & Light"

  - title: Community Water Systems
    graphic: http://placehold.it/350x350
    content: |
            Here is some content from subsection "Community Water Systems"

  - title: Compact & Complete Communities
    graphic: http://placehold.it/350x350
    content: |
            Here is some content from subsection "Compact & Complete Communities"

  - title: Housing Affordability
    graphic: http://placehold.it/350x350
    content: |
            Here is some content from subsection "Housing Affordability"

  - title: Infill & Redevelopment
    graphic: http://placehold.it/350x350
    content: |
            Here is some content from subsection "Infill & Redevelopment"

  - title: Public Spaces
    graphic: http://placehold.it/350x350
    content: |
            ### Park Access

            Austin was asked to demonstrate how our public spaces are sustainable in 14 areas. One of these areas pertains to access to parks and public spaces.

            ### Sustainability Benchmark

            Demonstrate that at least 70% of Austinites live within 1/3 mile walk of a park or public space, and that 90% live within 3 miles of an off-road trail.

            ### How Austin's Doing

            77% live within 1/3 mile walk of a park or public space.

            Austin excels in planning and design so that parks, public spaces, and off-road trails are highly accessible to a large majority of residents.

  - title: Transportation Choices
    graphic: http://placehold.it/350x350
    content: |
            Here is some content from subsection "Transportation Choices"
