title: Built Environment
description: A sustainable community provides quality, choice, and access in the built environment, where people live, work, and play.
lead: A sustainable built environment is characterized by
subsections:
  - title: Ambient Noise & Light
    graphic: http://placehold.it/350x350
    content: |
            Here is some content from subsection "Ambient Noise & Light"

  - title: Community Water Systems
    graphic: http://placehold.it/350x350
    content: |
            Here is some content from subsection "Community Water Systems"

  - title: Compact & Complete Communities
    graphic: http://placehold.it/350x350
    content: |
            Here is some content from subsection "Compact & Complete Communities"

  - title: Housing Affordability
    graphic: http://placehold.it/350x350
    content: |
            Here is some content from subsection "Housing Affordability"

  - title: Infill & Redevelopment
    graphic: http://placehold.it/350x350
    content: |
            Here is some content from subsection "Infill & Redevelopment"

  - title: Public Spaces
    graphic: http://placehold.it/350x350
    content: |
            Here is some content from subsection "Public Spaces"

  - title: Transportation Choices
    graphic: http://placehold.it/350x350
    content: |
            Here is some content from subsection "Transportation Choices"
