title: Built Environment
description: A sustainable community provides quality, choice, and access in the built environment, where people live, work, and play.
star: content/stars/home/identity_05_main-menu-07.png
lead: A sustainable built environment is characterized by
subsections:
  - title: Ambient Noise & Light
    description: Minimize and manage ambient noise and light levels to protect public health and integrity of ecological systems.
    star: content/stars/built_environment/identity_05-07_built-environment-2-01.png
    visualizations:
        - graphic: content/visualizations/placeholder350x350.gif
          title: Visualization Title
          description: Optional visualization description
    content: |
            Here is some content from subsection "Ambient Noise & Light"

  - title: Community Water Systems
    description: Provide a clean and secure water supply for all local users through the management of potable water, wastewater, stormwater, and other piped infrastructure.
    star: content/stars/built_environment/identity_05-07_built-environment-2-02.png
    visualizations:
        - graphic: content/visualizations/placeholder350x350.gif
          title: Visualization Title
          description: Optional visualization description
    content: |
            Here is some content from subsection "Community Water Systems"

  - title: Compact & Complete Communities
    description: Concentrate development in compact, human-scaled, walkable centers and neighborhoods that connect to transit, offer diverse uses and services, and provide housing options for families of all income.
    star: content/stars/built_environment/identity_05-07_built-environment-2-03.png
    visualizations:
        - graphic: content/visualizations/placeholder350x350.gif
          title: Visualization Title
          description: Optional visualization description
    content: |
            Here is some content from subsection "Compact & Complete Communities"

  - title: Housing Affordability
    description: Construct, preserve, and maintain an adequate and diverse supply of location-efficient and affordable housing options for all residents.
    star: content/stars/built_environment/identity_05-07_built-environment-2-04.png
    visualizations:
        - graphic: content/visualizations/placeholder350x350.gif
          title: Visualization Title
          description: Optional visualization description
    content: |
            Here is some content from subsection "Housing Affordability"

  - title: Infill & Redevelopment
    description: Focus new growth in infill areas and on development that does not require the extension of water, sewer, and road infrastructure or facilitate sprawl.
    star: content/stars/built_environment/identity_05-07_built-environment-2-05.png
    visualizations:
        - graphic: content/visualizations/placeholder350x350.gif
          title: Visualization Title
          description: Optional visualization description
    content: |
            Here is some content from subsection "Infill & Redevelopment"

  - title: Public Spaces
    description: Create a network of well-used and enjoyable parks and public spaces that feature equitable, convenient access for residents throughout the community.
    star: content/stars/built_environment/identity_05-07_built-environment-2-06.png
    visualizations:
        - graphic: content/visualizations/public-spaces_01.png
          title: Accessibility to Austin's Public Space
          description: Optional visualization description
        - graphic: content/visualizations/public-spaces_02.png
          title: Accessibility to Austin's Public Space
          description: Optional visualization description
        - graphic: content/visualizations/public-spaces_03.png
          title: Accessibility to Austin's Public Space
          description: Optional visualization description
    content: |
            #### Park Access

            Austin was asked to demonstrate how our public spaces are sustainable in 14 areas. One of these areas pertains to access to parks and public spaces.

            #### Sustainability Benchmark

            Demonstrate that at least 70% of Austinites live within 1/3 mile walk of a park or public space, and that 90% live within 3 miles of an off-road trail.

            #### How Austin's Doing

            77% live within 1/3 mile walk of a park or public space.

            Austin excels in planning and design so that parks, public spaces, and off-road trails are highly accessible to a large majority of residents.

            #### Bogus Content

            Lorem ipsum dolor sit amet, in cum timeam scripta, id luptatum splendide vis. No qui habeo exerci signiferumque. Nonumy option aliquip ea per, vis prima evertitur ei, tale errem consetetur vis id. Eum in enim ullamcorper voluptatibus. Ea wisi instructior vis, qui decore nostro adipisci cu.

            Et duo nostrud principes assentior, no habeo intellegat sententiae vim. Adhuc corpora nec et, aliquip minimum intellegebat no vis. Cu mollis iriure similique quo. Quis mollis usu ad, ad cum inani noster assueverit. Eam cibo munere cu, corpora abhorreant ius ex, omnes suscipit eam cu. Purto bonorum euripidis sit ea, adhuc dolores eu mel.

            Nec everti lucilius ea, ad nec stet minimum maiestatis. Clita putent viderer ei quo, at nemore copiosae est. Stet aeque menandri no vel, nullam debitis sea eu, causae partiendo pertinacia eos ea. Sit ne soleat docendi, reque consul delenit eam ad. Possit latine eum at, pri no facilis salutatus. Scripta quaestio moderatius nec eu, an posse aeterno pri. Saperet albucius scriptorem nam ad, at has magna autem.

            Natum veritus periculis ad vel, ei putent latine consectetuer has, vix ut erant mundi sanctus. Vis odio laoreet et. Mei alii oporteat pertinax ex. Eam ridens essent nostro ne. In qui dicat iisque blandit, maiorum consectetuer no est, eum ut oblique molestie similique.

            Ad iisque platonem eos, eam alii diceret euripidis id. Ex qui zril legendos, ferri lorem ut mea. Cum sale etiam saepe te. Lorem fabellas est in. Sea eu doming essent, aliquid gloriatur pertinacia eam at, ut nam mollis impedit tincidunt.


  - title: Transportation Choices
    description: Promote diverse transportation modes, including walking, bicycling, and transit, that are safe, low-cost, and reduce vehicle miles traveled.
    star: content/stars/built_environment/identity_05-07_built-environment-2-07.png
    visualizations:
        - graphic: content/visualizations/placeholder350x350.gif
          title: Visualization Title
          description: Optional visualization description
    content: |
            Here is some content from subsection "Transportation Choices"
